-- 1. ENUMS y CONFIGURACIONES
create type user_role as enum ('admin', 'supervisor', 'operario');
create type asset_status as enum ('operational', 'maintenance', 'broken', 'inactive');
create type wo_priority as enum ('low', 'medium', 'high', 'emergency');
create type wo_status as enum ('pending', 'approved', 'in_progress', 'completed', 'cancelled');

-- 2. PERFILES (Extiende auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  role user_role default 'operario',
  avatar_url text,
  created_at timestamptz default now()
);

-- 3. ACTIVOS (Maquinaria)
create table public.assets (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  criticality int not null check (criticality between 0 and 3), 
  status asset_status default 'operational',
  location text,
  image_url text,
  created_at timestamptz default now()
);

-- 4. INVENTARIO (Items/Repuestos)
create table public.inventory_items (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text,
  description text,
  current_stock int not null default 0,
  min_stock_alert int not null default 5,
  unit_cost numeric(10, 2) default 0, 
  location_in_warehouse text,
  updated_at timestamptz default now()
);

-- 5. CRONOGRAMA PREVENTIVO
create table public.maintenance_schedules (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) not null,
  title text not null, -- Ej: "Revisión Frenos Semestral"
  frequency_days int not null, -- Cada 180 días
  last_generated_date date,
  next_due_date date not null,
  is_active boolean default true
);

-- 6. ÓRDENES DE TRABAJO (Tabla Central)
create table public.work_orders (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) not null,
  
  -- Clasificación
  title text, -- Generado auto o manual
  description text,
  type text check (type in ('correctivo', 'preventivo')),
  priority wo_priority default 'medium',
  status wo_status default 'pending',
  
  -- Personas
  reported_by uuid references public.profiles(id),
  assigned_to uuid references public.profiles(id),
  
  -- Tiempos (KPIs)
  created_at timestamptz default now(),
  started_at timestamptz,
  completed_at timestamptz,
  
  -- Impacto
  is_machine_down boolean default false, -- ¿Paró la producción?
  solution_notes text
);

-- 7. CONSUMO DE ITEMS POR OT
create table public.work_order_items (
  id bigint generated by default as identity primary key,
  work_order_id bigint references public.work_orders(id) on delete cascade,
  item_id bigint references public.inventory_items(id) not null,
  quantity_used int not null check (quantity_used > 0),
  cost_at_moment numeric(10, 2) not null, -- Histórico de precio
  created_at timestamptz default now()
);
