-- ⚠️ ADVERTENCIA: ESTE SCRIPT BORRA TODOS LOS DATOS EXISTENTES ⚠️

-- 1. Limpieza inicial
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();
drop trigger if exists on_work_order_interlock on public.work_orders;
drop function if exists public.handle_asset_status_interlock();

-- Orden de borrado por dependencias (Hijo -> Padre)
drop table if exists public.daily_maintenance_logs cascade;
drop table if exists public.monthly_maintenance_sheets cascade;
drop table if exists public.maintenance_task_definitions cascade;
drop table if exists public.work_order_parts cascade;
drop table if exists public.inventory_movements cascade;
drop table if exists public.work_orders cascade;
drop table if exists public.operators cascade;
drop table if exists public.inventory_items cascade;
drop table if exists public.assets cascade;
drop table if exists public.profiles cascade;

-- Tipos y Enums
drop type if exists public.log_status;
drop type if exists public.maintenance_freq;
drop type if exists public.app_role;
drop type if exists public.movement_type;

-- 2. Configuración y Extensiones
create extension if not exists "uuid-ossp";

-- 3. Definición de Enums
create type public.app_role as enum ('admin', 'operator', 'supervisor');
create type public.maintenance_freq as enum ('diario', 'semanal', 'mensual', 'trimestral', 'semestral', 'anual');
create type public.log_status as enum ('completed', 'missed', 'failed', 'n/a'); 
-- 'completed': Hecho, 'missed': Olvidado, 'failed': Intentado pero falló, 'n/a': No aplica (ej: feriado)

-- 4. Tablas Base (Perfiles y Activos)

-- Profiles
create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text,
  role public.app_role default 'operator'::public.app_role,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Assets
create table public.assets (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  location text,
  type text,
  status text check (status in ('operational', 'maintenance', 'repair', 'retired')) default 'operational',
  serial_number text,
  model text,
  manufacturer text,
  purchase_date date,
  warranty_expiry date,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Tablas de Inventario y Work Orders

-- Inventory
create table public.inventory_items (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text unique not null,
  category text check (category in ('repuesto', 'consumible', 'herramienta')) not null,
  quantity integer default 0 not null,
  min_quantity integer default 0 not null,
  unit text not null,
  location text,
  price numeric(10, 2) default 0.00,
  supplier text,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Operators
create table public.operators (
  id bigint generated by default as identity primary key,
  full_name text not null,
  dni text unique not null,
  phone text,
  specialty text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Work Orders
create table public.work_orders (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  priority text check (priority in ('low', 'medium', 'high', 'critical')) default 'medium',
  status text check (status in ('pending', 'approved', 'in_progress', 'completed', 'cancelled')) default 'pending',
  type text check (type in ('preventive', 'corrective')) default 'corrective',
  asset_id bigint references public.assets(id),
  assigned_to uuid references public.profiles(id),
  operator_id bigint references public.operators(id),
  
  -- Tracking fields for metrics
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  downtime_hours numeric(10, 2) default 0,
  labor_hours numeric(10, 2) default 0,
  parts_cost numeric(10, 2) default 0,
  labor_cost numeric(10, 2) default 0,
  solution_notes text,
  failure_date timestamp with time zone default timezone('utc'::text, now()),
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Work Order Parts (Relación entre OT y Repuestos)
create table public.work_order_parts (
  id bigint generated by default as identity primary key,
  work_order_id bigint references public.work_orders(id) on delete cascade not null,
  inventory_item_id bigint references public.inventory_items(id) not null,
  quantity_used integer not null check (quantity_used > 0),
  unit_cost numeric(10, 2) default 0,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Inventory Movements (Tracking de movimientos de inventario)
create type public.movement_type as enum ('purchase', 'consumption', 'adjustment', 'return');

create table public.inventory_movements (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint references public.inventory_items(id) on delete cascade not null,
  movement_type public.movement_type not null,
  quantity integer not null, -- Puede ser negativo para consumos
  unit_cost numeric(10, 2) default 0,
  work_order_id bigint references public.work_orders(id),
  performed_by uuid references public.profiles(id),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Módulo de Mantenimiento Preventivo (Estructura Jerárquica)

-- A. Definiciones de Tareas (El "Plan")
create table public.maintenance_task_definitions (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) on delete cascade not null,
  component text not null, -- Ej: 'Bancada'
  task text not null,      -- Ej: 'Limpiar viruta'
  frequency public.maintenance_freq not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- B. Hoja Mensual (El "Contenedor" del mes)
create table public.monthly_maintenance_sheets (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) on delete cascade not null,
  month integer not null check (month between 1 and 12),
  year integer not null,
  
  status text check (status in ('generated', 'pending_upload', 'verified', 'rejected')) default 'generated',
  scan_url text, -- URL de la foto del papel
  
  performed_by uuid references public.profiles(id),
  verified_by uuid references public.profiles(id),
  observations text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(asset_id, month, year)
);

-- C. Logs Diarios (El "Detalle" para KPIs)
create table public.daily_maintenance_logs (
  id bigint generated by default as identity primary key,
  sheet_id bigint references public.monthly_maintenance_sheets(id) on delete cascade not null,
  task_def_id bigint references public.maintenance_task_definitions(id) not null,
  
  log_date date not null,
  status public.log_status default 'completed',
  notes text,
  
  -- Solo un log por tarea por día
  unique(sheet_id, task_def_id, log_date)
);

alter table public.work_orders enable row level security;
alter table public.work_order_parts enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.inventory_items enable row level security;
alter table public.profiles enable row level security;
alter table public.maintenance_task_definitions enable row level security;
alter table public.monthly_maintenance_sheets enable row level security;
alter table public.daily_maintenance_logs enable row level security;
alter table public.operators enable row level security;

-- Políticas "Permisivas" (Ajustar para producción)
create policy "Public access" on public.assets for all using (true);
create policy "Public access" on public.work_orders for all using (true);
create policy "Public access" on public.work_order_parts for all using (true);
create policy "Public access" on public.inventory_movements for all using (true);
create policy "Public access" on public.inventory_items for all using (true);
create policy "Public access" on public.maintenance_task_definitions for all using (true);
create policy "Public access" on public.monthly_maintenance_sheets for all using (true);
create policy "Public access" on public.daily_maintenance_logs for all using (true);
create policy "Public access" on public.operators for all using (true);

create policy "Public profiles" on public.profiles for select using (true);
create policy "User update own profile" on public.profiles for update using (auth.uid() = id);
create policy "User insert own profile" on public.profiles for insert with check (auth.uid() = id);

-- 8. Índices de Rendimiento

-- Índices para optimizar queries de métricas (MTBF/MTTR)
create index idx_work_orders_asset_completed on public.work_orders(asset_id, completed_at) where completed_at is not null;
create index idx_work_orders_type_status on public.work_orders(type, status, completed_at);
create index idx_work_orders_dates on public.work_orders(created_at, started_at, completed_at);

-- Índices para inventory movements
create index idx_inventory_movements_item_date on public.inventory_movements(inventory_item_id, created_at);
create index idx_inventory_movements_wo on public.inventory_movements(work_order_id) where work_order_id is not null;

-- 9. Triggers y Funciones
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'operator'::public.app_role);
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 10. Interlock de Estado de Activos (Nueva Funcionalidad)
create or replace function public.handle_asset_status_interlock()
returns trigger
language plpgsql
security definer
as $function$
declare
    target_asset_id int;
    active_corrective_count int;
    active_preventive_count int;
begin
    -- Determinar el asset_id afectado
    if (TG_OP = 'DELETE') then
        target_asset_id := old.asset_id;
    else
        target_asset_id := new.asset_id;
    end if;
    
    if target_asset_id is null then
        return new;
    end if;

    -- Contar OTs correctivas activas
    select count(*) into active_corrective_count
    from public.work_orders
    where asset_id = target_asset_id
    and status in ('pending', 'in_progress', 'approved')
    and type = 'corrective';

    -- Contar OTs preventivas activas
    select count(*) into active_preventive_count
    from public.work_orders
    where asset_id = target_asset_id
    and status in ('pending', 'in_progress', 'approved')
    and type = 'preventive';

    -- Aplicar lógica de prioridad
    if active_corrective_count > 0 then
        -- Hay falla activa -> REPAIR
        update public.assets 
        set status = 'repair' 
        where id = target_asset_id and status != 'retired';
    elsif active_preventive_count > 0 then
        -- Solo preventivo activo -> MAINTENANCE
        update public.assets 
        set status = 'maintenance' 
        where id = target_asset_id and status != 'retired'; 
    else
        -- No hay OTs activas -> OPERATIONAL
        update public.assets 
        set status = 'operational' 
        where id = target_asset_id and status != 'retired';
    end if;

    return new;
end;
$function$;

create trigger on_work_order_interlock
after insert or update of status, type, asset_id on public.work_orders
for each row execute procedure public.handle_asset_status_interlock();

insert into public.assets (name, location, type, status, model) values
('Torno Paralelo Wing', 'Taller Mecanizado', 'Torno', 'operational', 'L-2660'),
('Compresor A', 'Nave 1', 'Compresor', 'operational', 'CMP-500');

-- Definir tareas para el Torno (Basado en la imagen)
insert into public.maintenance_task_definitions (asset_id, component, task, frequency) values
(1, 'Bancada', 'Limpiar viruta', 'diario'),
(1, 'Bancada', 'Revisar obj. extraños', 'diario'),
(1, 'Bancada', 'Lubricar', 'diario'),
(1, 'Bancada', 'Reponer refrigerante', 'semanal'),
(1, 'Carro', 'Limpiar y lubricar guias', 'diario'),
(1, 'Carro', 'Limpiar portaherramientas', 'semanal'),
(1, 'Cabezal Fijo', 'Cambio aceite caja Norton', 'semestral');

-- Storage Bucket Configuration
insert into storage.buckets (id, name, public)
values ('app-images', 'app-images', true);

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'app-images' );

create policy "Authenticated users can upload"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'app-images' );

create policy "Authenticated users can update"
  on storage.objects for update
  to authenticated
  using ( bucket_id = 'app-images' );

create policy "Authenticated users can delete"
  on storage.objects for delete
  to authenticated
  using ( bucket_id = 'app-images' );
